language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
  - DJANGO_VERSION=\>=1.8,\<1.9
  - DJANGO_VERSION=\>=1.11,\<1.12
  - DJANGO_VERSION=\>=2.0,\<2.1
install:
  - pip install --upgrade pip
  - pip install Django$DJANGO_VERSION --upgrade
  - pip install -q -e .
  - pip install -q -r test-requirements.txt
script:
  - python -W module -m coverage run testproject/manage.py test fiber_test
after_success:
  - coveralls
branches:
  only:
    - master
    - dev
sudo: false
