language: python
sudo: false

# Travis config is driven by the tox.ini file.
# Here we just specify which Python versions to run tox with.
# Travis will start a CI server for each, and run all the tox
# environments that use that Python. So in Travis we are running both
# in parallel (one server per Python version) and in series
# (each server runs all the Django envs for that version of Python).
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis coverage coveralls

script:
  # Run against all the Python interpreter and Django versions specified in the tox.ini file.
  - tox

after_success:
  - coverage combine
  - COVERALLS_PARALLEL=true coveralls
